### ISSUE TITLE
What is the SE_{4}(3) group?

### ISSUE THREAD

**Issue by gtx818** [USTC-AIS-Lab/SI-LIO#3]
Interesting work! In your displaed supplementary video on Youtube, you introduce that you utilize the Lie exponential between the matrix Lie group SE$_4(3)$ and its Lie algebra for the linearization of the estimation error system and measurement residual, avoiding the introduction of the linearization errors in both estimate propagation and update process. What is the **SE$_4(3)$ matrix Lie group**?

**Comment by xixishui1999** [comment]
In SE(3), which includes rotation and translation, considering the addition of other states such as velocity, bias, and gravity, forms a larger group of the form [R | t v b_a b_g].

**Comment by chengwei0427** [comment]
Can you share the Youtube video link?

**Comment by gtx818** [comment]
> Can you share the Youtube video link?

It seems that the authors have removed the Youtube video.

**Comment by xixishui1999** [comment]
You can get links to the latest videos at https://www.youtube.com/watch?v=8JLsXeB0NGE **_OR_** https://www.bilibili.com/video/BV1fE421A7vZ/?spm_id_from=333.337.search-card.all.click&vd_source=d805ae3d03ba93f2b7355dbb0826b7ed
